<?php

namespace Usolv\TrackingBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
	public function findAllByProject($projectname)
	{
		$q = $this
		->createQueryBuilder('t')
		->select('t')
		->where('t.project_name = :project_name')
		->setParameter('project_name', $projectname)
		->getQuery();
	
		try {
			$tasks = $q->getResult();
		} catch (NoResultException $e) {
			$message = sprintf(
					'Unable to find an active admin UsolvTrackingBundle:Task object identified by "%s".',
					$projectname
			);
			throw new UsernameNotFoundException($message, 0, $e);
		}
	
		return $tasks;
	}
}
