<?php

namespace Usolv\TrackingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrackingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackingRepository extends EntityRepository
{}
