<?php

namespace Usolv\TrackingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WbsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WbsRepository extends EntityRepository
{
	public function findByProjectAutoOrdered($projectname)
	{
	  $query = $this->getEntityManager()
	    ->getRepository('UsolvTrackingBundle:Wbs')
      ->createQueryBuilder('w')
      ->where('w.project = :project_name')
      ->setParameter('project_name', $projectname)
      ->orderBy('w.order', 'ASC')
      ->getQuery();
	
	  try {
	    $wbsList = $query->getArrayResult();
	  } catch (NoResultException $e) {
	    $message = sprintf(
	        'Unable to find an active UsolvTrackingBundle:Wbs object identified by "%s".',
	        $projectname
	    );
	    throw new NoResultException($message, 0, $e);
	  }
	
	  return $wbsList;
	}
}